import type { SongData } from '../songs';

export const hiphop: SongData[] = [
  { title: "Lose Yourself",        artist: "Eminem",                    year: 2002 },
  { title: "God's Plan",           artist: "Drake",                     year: 2018 },
  { title: "Old Town Road",        artist: "Lil Nas X",                 year: 2019 },
  { title: "Rapper's Delight",     artist: "Sugarhill Gang",            year: 1979 },
  { title: "Fight the Power",      artist: "Public Enemy",              year: 1989 },
  { title: "California Love",      artist: "2Pac ft. Dr. Dre",          year: 1995 },
  { title: "Gangsta's Paradise",   artist: "Coolio",                    year: 1995 },
  { title: "Juicy",                artist: "The Notorious B.I.G.",      year: 1994 },
  { title: "99 Problems",          artist: "Jay-Z",                     year: 2003 },
  { title: "Empire State of Mind", artist: "Jay-Z ft. Alicia Keys",     year: 2009 },
  { title: "HUMBLE.",              artist: "Kendrick Lamar",            year: 2017 },
  { title: "Gold Digger",          artist: "Kanye West",                year: 2005 },
  { title: "Hotline Bling",        artist: "Drake",                     year: 2015 },
  { title: "Rockstar",             artist: "Post Malone",               year: 2017 },
  { title: "SICKO MODE",           artist: "Travis Scott",              year: 2018 },
      { title: "Nuthin' but a 'G' Thang", artist: "Dr. Dre ft. Snoop Dogg",     year: 1992 },
  { title: "Still D.R.E.",            artist: "Dr. Dre ft. Snoop Dogg",     year: 1999 },
  { title: "The Real Slim Shady",     artist: "Eminem",                     year: 2000 },
  { title: "Without Me",              artist: "Eminem",                     year: 2002 },
  { title: "Stan",                    artist: "Eminem ft. Dido",            year: 2000 },
  { title: "In Da Club",              artist: "50 Cent",                    year: 2003 },
  { title: "Many Men",                artist: "50 Cent",                    year: 2003 },
  { title: "P.I.M.P.",                artist: "50 Cent",                    year: 2003 },
  { title: "Drop It Like It's Hot",   artist: "Snoop Dogg ft. Pharrell",    year: 2004 },
  { title: "Gin and Juice",           artist: "Snoop Dogg",                 year: 1993 },
  { title: "Forgot About Dre",        artist: "Dr. Dre ft. Eminem",         year: 1999 },
  { title: "X Gon' Give It to Ya",    artist: "DMX",                        year: 2003 },
  { title: "Party Up (Up in Here)",   artist: "DMX",                        year: 1999 },
  { title: "Ms. Jackson",             artist: "OutKast",                    year: 2000 },
  { title: "Hey Ya!",                 artist: "OutKast",                    year: 2003 },
  { title: "Stronger",                artist: "Kanye West",                 year: 2007 },
  { title: "Power",                   artist: "Kanye West",                 year: 2010 },
  { title: "All of the Lights",       artist: "Kanye West",                 year: 2010 },
  { title: "Started From the Bottom", artist: "Drake",                      year: 2013 },
  { title: "One Dance",               artist: "Drake",                      year: 2016 },
  { title: "Nonstop",                 artist: "Drake",                      year: 2018 },
  { title: "Alright",                 artist: "Kendrick Lamar",             year: 2015 },
  { title: "DNA.",                    artist: "Kendrick Lamar",             year: 2017 },
  { title: "Swimming Pools (Drank)",  artist: "Kendrick Lamar",             year: 2012 },
  { title: "Mask Off",                artist: "Future",                     year: 2017 },
  { title: "Bad and Boujee",          artist: "Migos ft. Lil Uzi Vert",     year: 2016 },
  { title: "Suge",                    artist: "DaBaby",                     year: 2019 },
  { title: "ROXANNE",                 artist: "Arizona Zervas",             year: 2019 },
  { title: "Industry Baby",           artist: "Lil Nas X ft. Jack Harlow",  year: 2021 },
  { title: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X",          year: 2021 },
  { title: "WAP",                     artist: "Cardi B ft. Megan Thee Stallion", year: 2020 },
  { title: "Bodak Yellow",            artist: "Cardi B",                    year: 2017 },
  { title: "Savage",                  artist: "Megan Thee Stallion",        year: 2020 },
  { title: "Super Bass",              artist: "Nicki Minaj",                year: 2011 },
  { title: "Anaconda",                artist: "Nicki Minaj",                year: 2014 },
  { title: "Praise the Lord (Da Shine)", artist: "A$AP Rocky ft. Skepta",  year: 2018 },
  { title: "Goosebumps",              artist: "Travis Scott",               year: 2016 },
  { title: "Highest in the Room",     artist: "Travis Scott",               year: 2019 },
  { title: "Lucid Dreams",            artist: "Juice WRLD",                 year: 2018 },
  { title: "All Girls Are the Same",  artist: "Juice WRLD",                 year: 2018 },
  { title: "XO TOUR Llif3",           artist: "Lil Uzi Vert",               year: 2017 },
  { title: "Money Longer",            artist: "Lil Uzi Vert",               year: 2016 },
  { title: "Hate It or Love It",      artist: "The Game ft. 50 Cent",       year: 2005 },
  { title: "No Role Modelz",          artist: "J. Cole",                    year: 2014 },
  { title: "Middle Child",            artist: "J. Cole",                    year: 2019 },
  { title: "Wet Dreamz",              artist: "J. Cole",                    year: 2014 },
  { title: "A Milli",                 artist: "Lil Wayne",                  year: 2008 },
  { title: "Lollipop",                artist: "Lil Wayne",                  year: 2008 },
  { title: "Forever",                 artist: "Drake, Kanye West, Lil Wayne & Eminem", year: 2009 },
  { title: "Run This Town",           artist: "Jay-Z ft. Rihanna & Kanye West", year: 2009 },

  { title: "La Di Da Di",            artist: "Slick Rick & Doug E. Fresh", year: 1985 },
  { title: "The Breaks",             artist: "Kurtis Blow",                year: 1980 },
  { title: "Basketball",             artist: "Kurtis Blow",                year: 1984 },
  { title: "I Need Love",            artist: "LL Cool J",                  year: 1987 },
  { title: "Mama Said Knock You Out",artist: "LL Cool J",                  year: 1990 },
  { title: "Rock the Bells",         artist: "LL Cool J",                  year: 1985 },
  { title: "Eric B. Is President",   artist: "Eric B. & Rakim",            year: 1986 },
  { title: "Paid in Full",           artist: "Eric B. & Rakim",            year: 1987 },
  { title: "Follow the Leader",      artist: "Eric B. & Rakim",            year: 1988 },
  { title: "Paul Revere",            artist: "Beastie Boys",               year: 1986 },
  { title: "Fight for Your Right",   artist: "Beastie Boys",               year: 1986 },
  { title: "No Sleep Till Brooklyn", artist: "Beastie Boys",               year: 1986 },
  { title: "Me Myself and I",        artist: "De La Soul",                 year: 1989 },
  { title: "Buddy",                  artist: "De La Soul",                 year: 1989 },
  { title: "Scenario",               artist: "A Tribe Called Quest",       year: 1991 },
  { title: "Can I Kick It?",         artist: "A Tribe Called Quest",       year: 1990 },
  { title: "Electric Relaxation",    artist: "A Tribe Called Quest",       year: 1993 },
  { title: "They Reminisce Over You (T.R.O.Y.)", artist: "Pete Rock & CL Smooth", year: 1992 },
  { title: "Rebel Without a Pause",  artist: "Public Enemy",               year: 1987 },
];
