import type { SongData } from '../songs';

export const metal: SongData[] = [
  { title: "Crazy Train",      artist: "Ozzy Osbourne",  year: 1980 },
  { title: "Enter Sandman",    artist: "Metallica",      year: 1991 },
  { title: "Master of Puppets", artist: "Metallica",     year: 1986 },
  { title: "Paranoid",         artist: "Black Sabbath",  year: 1970 },
  { title: "Iron Man",         artist: "Black Sabbath",  year: 1970 },
  { title: "Run to the Hills", artist: "Iron Maiden",    year: 1982 },
  { title: "In the End",       artist: "Linkin Park",    year: 2000 },
  { title: "Numb",             artist: "Linkin Park",    year: 2003 },
      { title: "Hallowed Be Thy Name",    artist: "Iron Maiden",       year: 1982 },
  { title: "The Trooper",             artist: "Iron Maiden",       year: 1983 },
  { title: "Fear of the Dark",        artist: "Iron Maiden",       year: 1992 },
  { title: "Ace of Spades",           artist: "Motörhead",         year: 1980 },
  { title: "Overkill",                artist: "Motörhead",         year: 1979 },
  { title: "Painkiller",              artist: "Judas Priest",      year: 1990 },
  { title: "Breaking the Law",        artist: "Judas Priest",      year: 1980 },
  { title: "Living After Midnight",   artist: "Judas Priest",      year: 1978 },
  { title: "Symphony of Destruction", artist: "Megadeth",         year: 1992 },
  { title: "Peace Sells",             artist: "Megadeth",         year: 1986 },
  { title: "Holy Wars… The Punishment Due", artist: "Megadeth",   year: 1990 },
  { title: "South of Heaven",         artist: "Slayer",           year: 1988 },
  { title: "Raining Blood",           artist: "Slayer",           year: 1986 },
  { title: "Angel of Death",          artist: "Slayer",           year: 1986 },
  { title: "Duality",                 artist: "Slipknot",         year: 2004 },
  { title: "Psychosocial",            artist: "Slipknot",         year: 2008 },
  { title: "Wait and Bleed",          artist: "Slipknot",         year: 1999 },
  { title: "Chop Suey!",              artist: "System of a Down", year: 2001 },
  { title: "Toxicity",                artist: "System of a Down", year: 2001 },
  { title: "B.Y.O.B.",                 artist: "System of a Down", year: 2005 },
  { title: "Blackened",               artist: "Metallica",        year: 1988 },
  { title: "Fade to Black",           artist: "Metallica",        year: 1984 },
  { title: "One",                     artist: "Metallica",        year: 1988 },
  { title: "Battery",                  artist: "Metallica",       year: 1986 },
  { title: "Welcome Home (Sanitarium)", artist: "Metallica",      year: 1986 },
  { title: "Holy Diver",              artist: "Dio",              year: 1983 },
  { title: "Rainbow in the Dark",     artist: "Dio",              year: 1983 },
  { title: "Man on the Silver Mountain", artist: "Rainbow",       year: 1975 },
  { title: "Kill the King",           artist: "Rainbow",          year: 1978 },
  { title: "Mirror Mirror",           artist: "Blind Guardian",   year: 1998 },
  { title: "Valhalla",                artist: "Blind Guardian",   year: 1988 },
  { title: "Through the Fire and Flames", artist: "DragonForce",  year: 2006 },
  { title: "Fury of the Storm",       artist: "DragonForce",      year: 2004 },
  { title: "Cowboys from Hell",       artist: "Pantera",          year: 1990 },
  { title: "Walk",                    artist: "Pantera",          year: 1992 },
  { title: "Cemetery Gates",          artist: "Pantera",          year: 1990 },
  { title: "Domination",              artist: "Pantera",          year: 1990 },
  { title: "Seasons in the Abyss",    artist: "Slayer",           year: 1990 },
  { title: "Black Label",             artist: "Machine Head",     year: 1994 },
  { title: "A Tout Le Monde",         artist: "Megadeth",         year: 1994 },
  { title: "Bleed",                   artist: "Meshuggah",        year: 2008 },
  { title: "New Millennium Cyanide Christ", artist: "Meshuggah",   year: 1998 },
  { title: "Bodies",                  artist: "Drowning Pool",    year: 2001 },
  { title: "Prayer",                  artist: "Disturbed",        year: 2000 },
  { title: "Down with the Sickness",  artist: "Disturbed",        year: 2000 },
  { title: "Inside the Fire",         artist: "Disturbed",        year: 2008 },
  { title: "Laid to Rest",            artist: "Lamb of God",      year: 2004 },
  { title: "Redneck",                 artist: "Lamb of God",      year: 2006 },
  { title: "Black Widow",             artist: "In This Moment",   year: 2014 },
  { title: "I Am the Fire",           artist: "Halestorm",        year: 2012 },
  { title: "Love Bites (So Do I)",    artist: "Halestorm",        year: 2012 },
  { title: "Only for the Weak",        artist: "In Flames",         year: 2000 },
  { title: "Take This Life",           artist: "In Flames",         year: 2006 },
  { title: "Trigger",                  artist: "In Flames",         year: 2002 },
  { title: "Cloud Connected",          artist: "In Flames",         year: 2002 },
  { title: "The Jester Race",          artist: "In Flames",         year: 1996 },
  { title: "Moonshield",               artist: "In Flames",         year: 1996 },
  { title: "ThereIn",                   artist: "Dark Tranquillity", year: 1999 },
  { title: "The Treason Wall",         artist: "Dark Tranquillity", year: 1995 },
  { title: "The Silence in Between",   artist: "In Flames",         year: 2014 },
  { title: "Ropes",                     artist: "In Flames",         year: 2014 },
  { title: "Fearless",                  artist: "In Flames",         year: 2019 },
  { title: "I, the Mask",               artist: "In Flames",         year: 2019 },
  { title: "We Rule the Night",        artist: "Soilwork",          year: 2007 },
];
