import type { SongData } from '../songs';

export const pop: SongData[] = [
  { title: "Billie Jean",                   artist: "Michael Jackson",             year: 1983 },
  { title: "Rolling in the Deep",           artist: "Adele",                       year: 2010 },
  { title: "Shape of You",                  artist: "Ed Sheeran",                  year: 2017 },
  { title: "Blinding Lights",               artist: "The Weeknd",                  year: 2019 },
  { title: "Someone Like You",              artist: "Adele",                       year: 2011 },
  { title: "Uptown Funk",                   artist: "Mark Ronson ft. Bruno Mars",  year: 2014 },
  { title: "Happy",                         artist: "Pharrell Williams",           year: 2013 },
  { title: "Despacito",                     artist: "Luis Fonsi ft. Daddy Yankee", year: 2017 },
  { title: "Can't Stop the Feeling",        artist: "Justin Timberlake",           year: 2016 },
  { title: "Thriller",                      artist: "Michael Jackson",             year: 1982 },
  { title: "Baby One More Time",            artist: "Britney Spears",              year: 1998 },
  { title: "Toxic",                         artist: "Britney Spears",              year: 2003 },
  { title: "Bad Romance",                   artist: "Lady Gaga",                   year: 2009 },
  { title: "Poker Face",                    artist: "Lady Gaga",                   year: 2008 },
  { title: "Crazy in Love",                 artist: "Beyoncé",                     year: 2003 },
  { title: "Halo",                          artist: "Beyoncé",                     year: 2008 },
  { title: "Love Story",                    artist: "Taylor Swift",                year: 2008 },
  { title: "Shake It Off",                  artist: "Taylor Swift",                year: 2014 },
  { title: "Blank Space",                   artist: "Taylor Swift",                year: 2014 },
  { title: "Levitating",                    artist: "Dua Lipa",                    year: 2020 },
  { title: "Don't Start Now",               artist: "Dua Lipa",                    year: 2019 },
  { title: "Thank U, Next",                 artist: "Ariana Grande",               year: 2018 },
  { title: "7 Rings",                       artist: "Ariana Grande",               year: 2019 },
  { title: "Call Me Maybe",                 artist: "Carly Rae Jepsen",            year: 2011 },
  { title: "Gangnam Style",                 artist: "PSY",                         year: 2012 },
  { title: "Beat It",                       artist: "Michael Jackson",             year: 1982 },
  { title: "Man in the Mirror",             artist: "Michael Jackson",             year: 1987 },
  { title: "I Will Always Love You",        artist: "Whitney Houston",             year: 1992 },
  { title: "I Wanna Dance with Somebody",   artist: "Whitney Houston",             year: 1987 },
  { title: "All I Want for Christmas Is You", artist: "Mariah Carey",             year: 1994 },
      { title: "Like a Prayer",              artist: "Madonna",                    year: 1989 },
  { title: "Vogue",                     artist: "Madonna",                    year: 1990 },
  { title: "Material Girl",             artist: "Madonna",                    year: 1984 },
  { title: "Firework",                  artist: "Katy Perry",                 year: 2010 },
  { title: "Teenage Dream",             artist: "Katy Perry",                 year: 2010 },
  { title: "Roar",                      artist: "Katy Perry",                 year: 2013 },
  { title: "Dark Horse",                artist: "Katy Perry",                 year: 2013 },
  { title: "Since U Been Gone",         artist: "Kelly Clarkson",             year: 2004 },
  { title: "Stronger (What Doesn't Kill You)", artist: "Kelly Clarkson",     year: 2011 },
  { title: "Umbrella",                  artist: "Rihanna ft. Jay-Z",          year: 2007 },
  { title: "We Found Love",             artist: "Rihanna ft. Calvin Harris",  year: 2011 },
  { title: "Diamonds",                  artist: "Rihanna",                    year: 2012 },
  { title: "Stay",                      artist: "Rihanna ft. Mikky Ekko",     year: 2013 },
  { title: "Counting Stars",            artist: "OneRepublic",                year: 2013 },
  { title: "Apologize",                 artist: "OneRepublic",                year: 2007 },
  { title: "Closer",                    artist: "The Chainsmokers ft. Halsey",year: 2016 },
  { title: "Something Just Like This",  artist: "The Chainsmokers & Coldplay",year: 2017 },
  { title: "Havana",                    artist: "Camila Cabello",             year: 2017 },
  { title: "Señorita",                  artist: "Shawn Mendes & Camila Cabello",year: 2019 },
  { title: "Treat You Better",          artist: "Shawn Mendes",               year: 2016 },
  { title: "Sorry",                     artist: "Justin Bieber",              year: 2015 },
  { title: "Love Yourself",             artist: "Justin Bieber",              year: 2015 },
  { title: "Peaches",                   artist: "Justin Bieber ft. Daniel Caesar & Giveon", year: 2021 },
  { title: "As It Was",                 artist: "Harry Styles",               year: 2022 },
  { title: "Watermelon Sugar",          artist: "Harry Styles",               year: 2019 },
  { title: "Adore You",                 artist: "Harry Styles",               year: 2019 },
  { title: "Drivers License",           artist: "Olivia Rodrigo",             year: 2021 },
  { title: "Good 4 U",                  artist: "Olivia Rodrigo",             year: 2021 },
  { title: "Stay",                      artist: "The Kid LAROI & Justin Bieber", year: 2021 },
  { title: "Flowers",                   artist: "Miley Cyrus",                year: 2023 },
  { title: "Party in the U.S.A.",       artist: "Miley Cyrus",                year: 2009 },
  { title: "Wrecking Ball",             artist: "Miley Cyrus",                year: 2013 },
  { title: "Tik Tok",                   artist: "Kesha",                      year: 2009 },
  { title: "Die Young",                 artist: "Kesha",                      year: 2012 },
  { title: "Just the Way You Are",      artist: "Bruno Mars",                 year: 2010 },
  { title: "Grenade",                   artist: "Bruno Mars",                 year: 2010 },
  { title: "Locked Out of Heaven",      artist: "Bruno Mars",                 year: 2012 },
  { title: "That's What I Like",        artist: "Bruno Mars",                 year: 2017 },
  { title: "Treasure",                  artist: "Bruno Mars",                 year: 2013 },
  { title: "Can't Feel My Face",        artist: "The Weeknd",                 year: 2015 },
  { title: "Starboy",                   artist: "The Weeknd ft. Daft Punk",   year: 2016 },
  { title: "Take On Me",                artist: "a-ha",                       year: 1985 },
  { title: "Wake Me Up Before You Go-Go", artist: "Wham!",                   year: 1984 },
  { title: "Careless Whisper",          artist: "George Michael",             year: 1984 },
  { title: "Dancing Queen",             artist: "ABBA",                       year: 1976 },
  { title: "Gimme! Gimme! Gimme!",      artist: "ABBA",                       year: 1979 },
  { title: "Take a Chance on Me",       artist: "ABBA",                       year: 1978 },
  { title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys",      year: 1997 },
  { title: "I Want It That Way",        artist: "Backstreet Boys",            year: 1999 },
  { title: "Bye Bye Bye",               artist: "*NSYNC",                     year: 2000 },
  { title: "It's Gonna Be Me",          artist: "*NSYNC",                     year: 2000 },
  { title: "Genie in a Bottle",         artist: "Christina Aguilera",         year: 1999 },
  { title: "Beautiful",                 artist: "Christina Aguilera",         year: 2002 },
  { title: "Say My Name",               artist: "Destiny's Child",            year: 1999 },
  { title: "No Scrubs",                 artist: "TLC",                        year: 1999 },
  { title: "Waterfalls",                artist: "TLC",                        year: 1995 },
  { title: "Unwritten",                 artist: "Natasha Bedingfield",        year: 2004 },
  { title: "Pocketful of Sunshine",     artist: "Natasha Bedingfield",        year: 2008 },
  { title: "Price Tag",                 artist: "Jessie J ft. B.o.B",         year: 2011 },
  { title: "Domino",                    artist: "Jessie J",                   year: 2011 },
  { title: "Chandelier",                artist: "Sia",                        year: 2014 },
  { title: "Cheap Thrills",             artist: "Sia",                        year: 2016 },
  { title: "Royals",                    artist: "Lorde",                      year: 2013 },
  { title: "Team",                      artist: "Lorde",                      year: 2013 },
  { title: "Espresso",                  artist: "Sabrina Carpenter",          year: 2024 },
  { title: "Please Please Please",      artist: "Sabrina Carpenter",          year: 2024 },
  { title: "Feather",                   artist: "Sabrina Carpenter",          year: 2023 },
  { title: "Greedy",                    artist: "Tate McRae",                 year: 2023 },
  { title: "Exes",                      artist: "Tate McRae",                 year: 2023 },
  { title: "Houdini",                   artist: "Dua Lipa",                   year: 2023 },
  { title: "Training Season",           artist: "Dua Lipa",                   year: 2024 },
  { title: "Illusion",                  artist: "Dua Lipa",                   year: 2024 },
  { title: "Fortnight",                 artist: "Taylor Swift ft. Post Malone", year: 2024 },
  { title: "Cruel Summer",              artist: "Taylor Swift",               year: 2019 },
  { title: "Is It Over Now?",           artist: "Taylor Swift",               year: 2023 },
  { title: "Paint the Town Red",        artist: "Doja Cat",                   year: 2023 },
  { title: "Agora Hills",               artist: "Doja Cat",                   year: 2023 },
  { title: "Yes, And?",                 artist: "Ariana Grande",              year: 2024 },
  { title: "We Can't Be Friends (Wait for Your Love)", artist: "Ariana Grande", year: 2024 },
  { title: "Beautiful Things",          artist: "Benson Boone",               year: 2024 },
  { title: "Slow It Down",              artist: "Benson Boone",               year: 2024 },
  { title: "Too Sweet",                 artist: "Hozier",                     year: 2024 },
  { title: "Lose Control",              artist: "Teddy Swims",                year: 2023 },
  { title: "Stick Season",              artist: "Noah Kahan",                 year: 2022 },
  { title: "Dial Drunk",                artist: "Noah Kahan",                 year: 2023 },
  { title: "What Was I Made For?",      artist: "Billie Eilish",              year: 2023 },
  { title: "Lunch",                     artist: "Billie Eilish",              year: 2024 },
  { title: "Birds of a Feather",        artist: "Billie Eilish",              year: 2024 },
  { title: "End of Beginning",          artist: "Djo",                        year: 2022 },
  { title: "Daylight",                  artist: "David Kushner",              year: 2023 },
  { title: "Strangers",                 artist: "Kenya Grace",                year: 2023 },
  { title: "Prada",                     artist: "cassö, RAYE & D-Block Europe", year: 2023 },
  { title: "Messy",                     artist: "Lola Young",                 year: 2024 },
  { title: "Water",                     artist: "Tyla",                       year: 2023 },

  // Obscure / deep cuts
  { title: "Fade to Grey",              artist: "Visage",                  year: 1980 },
  { title: "Tainted Love",              artist: "Soft Cell",               year: 1981 },
  { title: "Don't You Want Me",         artist: "The Human League",        year: 1981 },
  { title: "Blue Monday",               artist: "New Order",               year: 1983 },
  { title: "West End Girls",            artist: "Pet Shop Boys",           year: 1984 },
  { title: "It's My Life",              artist: "Talk Talk",               year: 1984 },
  { title: "You Spin Me Round",         artist: "Dead or Alive",           year: 1984 },
  { title: "Smalltown Boy",             artist: "Bronski Beat",            year: 1984 },
  { title: "Shout",                     artist: "Tears for Fears",         year: 1984 },
  { title: "Lovefool",                  artist: "The Cardigans",           year: 1996 },
  { title: "Lovesong",                  artist: "The Cure",                year: 1989 },
  { title: "Bizarre Love Triangle",     artist: "New Order",               year: 1986 },
  { title: "Just Like Heaven",          artist: "The Cure",                year: 1987 },
  { title: "99 Luftballons",            artist: "Nena",                    year: 1983 },
  { title: "Vienna",                    artist: "Ultravox",                year: 1981 },
  { title: "Electricity",               artist: "OMD",                     year: 1980 },
  { title: "Enola Gay",                 artist: "OMD",                     year: 1980 },
  { title: "I Ran",                     artist: "A Flock of Seagulls",     year: 1982 },
  { title: "Too Shy",                   artist: "Kajagoogoo",              year: 1983 },
  { title: "Our House",                 artist: "Madness",                 year: 1982 },
];
