import type { SongData } from '../songs';

export const rock: SongData[] = [
  { title: "Bohemian Rhapsody",         artist: "Queen",                 year: 1975 },
  { title: "Smells Like Teen Spirit",   artist: "Nirvana",               year: 1991 },
  { title: "Like a Rolling Stone",      artist: "Bob Dylan",             year: 1965 },
  { title: "Hotel California",          artist: "Eagles",                year: 1977 },
  { title: "Born to Run",              artist: "Bruce Springsteen",      year: 1975 },
  { title: "Johnny B. Goode",          artist: "Chuck Berry",            year: 1958 },
  { title: "Imagine",                  artist: "John Lennon",            year: 1971 },
  { title: "Yesterday",               artist: "The Beatles",             year: 1965 },
  { title: "Hey Jude",                artist: "The Beatles",             year: 1968 },
  { title: "Stairway to Heaven",      artist: "Led Zeppelin",            year: 1971 },
  { title: "Angie",                   artist: "The Rolling Stones",      year: 1973 },
  { title: "Jump",                    artist: "Van Halen",               year: 1984 },
  { title: "Sweet Child O' Mine",     artist: "Guns N' Roses",           year: 1987 },
  { title: "Don't Stop Believin'",    artist: "Journey",                 year: 1981 },
  { title: "Eye of the Tiger",        artist: "Survivor",                year: 1982 },
  { title: "Back in Black",           artist: "AC/DC",                   year: 1980 },
  { title: "Highway to Hell",         artist: "AC/DC",                   year: 1979 },
  { title: "Thunderstruck",           artist: "AC/DC",                   year: 1990 },
  { title: "Wonderwall",             artist: "Oasis",                    year: 1995 },
  { title: "Yellow",                 artist: "Coldplay",                 year: 2000 },
  { title: "With or Without You",    artist: "U2",                       year: 1987 },
  { title: "One",                    artist: "U2",                       year: 1991 },
  { title: "Seven Nation Army",      artist: "The White Stripes",        year: 2003 },
  { title: "Mr. Brightside",         artist: "The Killers",              year: 2003 },
  { title: "Under the Bridge",       artist: "Red Hot Chili Peppers",    year: 1992 },
  { title: "Creep",                  artist: "Radiohead",                year: 1992 },
  { title: "Black Hole Sun",         artist: "Soundgarden",              year: 1994 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day",           year: 2004 },
  { title: "Welcome to the Jungle",  artist: "Guns N' Roses",            year: 1987 },
  { title: "November Rain",          artist: "Guns N' Roses",            year: 1991 },
  { title: "Whole Lotta Love",       artist: "Led Zeppelin",             year: 1969 },
  { title: "Smoke on the Water",     artist: "Deep Purple",              year: 1972 },
  { title: "Roxanne",                artist: "The Police",               year: 1978 },
  { title: "Paint It Black",           artist: "The Rolling Stones",      year: 1966 },
  { title: "Gimme Shelter",            artist: "The Rolling Stones",      year: 1969 },
  { title: "London Calling",           artist: "The Clash",               year: 1979 },
  { title: "Should I Stay or Should I Go", artist: "The Clash",          year: 1982 },
  { title: "Another Brick in the Wall",artist: "Pink Floyd",              year: 1979 },
  { title: "Comfortably Numb",         artist: "Pink Floyd",              year: 1979 },
  { title: "Wish You Were Here",       artist: "Pink Floyd",              year: 1975 },
  { title: "Karma Police",             artist: "Radiohead",               year: 1997 },
  { title: "Paranoid Android",         artist: "Radiohead",               year: 1997 },
  { title: "All the Small Things",     artist: "Blink-182",               year: 1999 },
  { title: "I Miss You",               artist: "Blink-182",               year: 2004 },
  { title: "American Idiot",           artist: "Green Day",               year: 2004 },
  { title: "Basket Case",              artist: "Green Day",               year: 1994 },
  { title: "The Pretender",            artist: "Foo Fighters",            year: 2007 },
  { title: "Everlong",                 artist: "Foo Fighters",            year: 1997 },
  { title: "Learn to Fly",             artist: "Foo Fighters",            year: 1999 },
  { title: "Take Me Out",              artist: "Franz Ferdinand",         year: 2004 },
  { title: "Do I Wanna Know?",         artist: "Arctic Monkeys",          year: 2013 },
  { title: "R U Mine?",                artist: "Arctic Monkeys",          year: 2012 },
  { title: "Sex on Fire",              artist: "Kings of Leon",           year: 2008 },
  { title: "Use Somebody",             artist: "Kings of Leon",           year: 2008 },
  { title: "Clocks",                   artist: "Coldplay",                year: 2002 },
  { title: "Viva La Vida",             artist: "Coldplay",                year: 2008 },
  { title: "Time Is Running Out",      artist: "Muse",                    year: 2003 },
  { title: "Uprising",                 artist: "Muse",                    year: 2009 },
  { title: "Supermassive Black Hole",  artist: "Muse",                    year: 2006 },
  { title: "No One Knows",             artist: "Queens of the Stone Age", year: 2002 },
  { title: "Go With the Flow",         artist: "Queens of the Stone Age", year: 2003 },
  { title: "Are You Gonna Be My Girl", artist: "Jet",                     year: 2003 },
  { title: "Last Nite",                artist: "The Strokes",             year: 2001 },
  { title: "Reptilia",                 artist: "The Strokes",             year: 2003 },
  { title: "This Love",                artist: "Maroon 5",                year: 2004 },
  { title: "Hard to Explain",          artist: "The Strokes",             year: 2001 },
  { title: "Feel Good Inc.",           artist: "Gorillaz",                year: 2005 },
  { title: "Song 2",                   artist: "Blur",                    year: 1997 },
  { title: "Coffee & TV",              artist: "Blur",                    year: 1999 },
  { title: "Plug In Baby",             artist: "Muse",                    year: 2001 },
  { title: "Chasing Cars",             artist: "Snow Patrol",             year: 2006 },
  { title: "Run",                      artist: "Snow Patrol",             year: 2003 },
  { title: "How You Remind Me",        artist: "Nickelback",              year: 2001 },
  { title: "Bring Me to Life",         artist: "Evanescence",             year: 2003 },
  { title: "My Immortal",              artist: "Evanescence",             year: 2003 },
  { title: "Teenage Dirtbag",          artist: "Wheatus",                 year: 2000 },
  { title: "Zombie",                   artist: "The Cranberries",         year: 1994 },
  { title: "Linger",                   artist: "The Cranberries",         year: 1993 },
  { title: "Iris",                     artist: "Goo Goo Dolls",           year: 1998 },
  { title: "Drive",                    artist: "Incubus",                 year: 2000 },
  { title: "Scar Tissue",              artist: "Red Hot Chili Peppers",   year: 1999 },
  { title: "Californication",          artist: "Red Hot Chili Peppers",   year: 1999 },
  { title: "By the Way",               artist: "Red Hot Chili Peppers",   year: 2002 },
  { title: "The Scientist",            artist: "Coldplay",                year: 2002 },
  { title: "Fix You",                  artist: "Coldplay",                year: 2005 },
  { title: "Runaway Train",            artist: "Soul Asylum",             year: 1992 },
  { title: "Alive",                    artist: "Pearl Jam",               year: 1991 },
  { title: "Even Flow",                artist: "Pearl Jam",               year: 1991 },
  { title: "Jeremy",                   artist: "Pearl Jam",               year: 1992 },
  { title: "Come As You Are",          artist: "Nirvana",                 year: 1991 },
  { title: "Lithium",                  artist: "Nirvana",                 year: 1992 },
  { title: "The Man Who Sold the World", artist: "Nirvana",              year: 1994 },
  { title: "Where Is My Mind?",        artist: "Pixies",                  year: 1988 },
  { title: "Take on Me",               artist: "a-ha",                    year: 1985 },
  { title: "Africa",                   artist: "Toto",                    year: 1982 },
  { title: "Rosanna",                  artist: "Toto",                    year: 1982 },
  { title: "Don't You (Forget About Me)", artist: "Simple Minds",        year: 1985 },
  { title: "Every Breath You Take",    artist: "The Police",              year: 1983 },
  { title: "Message in a Bottle",      artist: "The Police",              year: 1979 },
  { title: "Dream On",                 artist: "Aerosmith",               year: 1973 },
  { title: "Walk This Way",            artist: "Aerosmith",               year: 1975 },
  { title: "Livin' on a Prayer",       artist: "Bon Jovi",                year: 1986 },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi",                year: 1986 },
  { title: "Run to the Hills",         artist: "Iron Maiden",             year: 1982 },
  { title: "Paranoid",                 artist: "Black Sabbath",           year: 1970 },
  { title: "Iron Man",                 artist: "Black Sabbath",           year: 1970 },
  { title: "Ace of Spades",            artist: "Motörhead",               year: 1980 },
  { title: "Killing in the Name",      artist: "Rage Against the Machine",year: 1992 },
  { title: "Bulls on Parade",          artist: "Rage Against the Machine",year: 1996 },
  { title: "Seven Seas of Rhye",       artist: "Queen",                   year: 1974 },
  { title: "We Will Rock You",         artist: "Queen",                   year: 1977 },
  { title: "We Are the Champions",     artist: "Queen",                   year: 1977 },

  // Obscure / deep cuts
  { title: "Astronomy Domine",          artist: "Pink Floyd",              year: 1967 },
  { title: "The Drowned World",         artist: "Gary Numan",              year: 1979 },
  { title: "Only Shallow",              artist: "My Bloody Valentine",     year: 1991 },
  { title: "When the Levee Breaks",     artist: "Led Zeppelin",            year: 1971 },
  { title: "Sister Ray",                artist: "The Velvet Underground",  year: 1968 },
  { title: "Fox on the Run",            artist: "Sweet",                   year: 1975 },
  { title: "Rebel Rebel",               artist: "David Bowie",             year: 1974 },
  { title: "All Tomorrow's Parties",    artist: "The Velvet Underground",  year: 1967 },
  { title: "Transmission",              artist: "Joy Division",            year: 1979 },
  { title: "She Sells Sanctuary",       artist: "The Cult",                year: 1985 },
  { title: "Cities in Dust",            artist: "Siouxsie and the Banshees", year: 1985 },
  { title: "Gigantic",                  artist: "Pixies",                  year: 1988 },
  { title: "Debaser",                   artist: "Pixies",                  year: 1989 },
  { title: "Cavalcade",                 artist: "The Mars Volta",          year: 2005 },
  { title: "Cut Your Hair",             artist: "Pavement",                year: 1994 },
  { title: "Gold Soundz",               artist: "Pavement",                year: 1994 },
  { title: "Celebrity Skin",            artist: "Hole",                    year: 1998 },
  { title: "Cannonball",                artist: "The Breeders",            year: 1993 },
  { title: "Maps",                      artist: "Yeah Yeah Yeahs",         year: 2003 },
  { title: "Reptilia",                  artist: "The Strokes",             year: 2003 },
];
