import type { SongData } from '../songs';

export const soul: SongData[] = [
  { title: "Purple Rain",                              artist: "Prince",                        year: 1984 },
  { title: "Superstition",                             artist: "Stevie Wonder",                 year: 1972 },
  { title: "Respect",                                  artist: "Aretha Franklin",               year: 1967 },
  { title: "What's Going On",                          artist: "Marvin Gaye",                   year: 1971 },
  { title: "I Got You (I Feel Good)",                  artist: "James Brown",                   year: 1965 },
  { title: "Let's Get It On",                          artist: "Marvin Gaye",                   year: 1973 },
  { title: "Sexual Healing",                           artist: "Marvin Gaye",                   year: 1982 },
  { title: "Sir Duke",                                 artist: "Stevie Wonder",                 year: 1976 },
  { title: "Papa Was a Rollin' Stone",                 artist: "The Temptations",               year: 1972 },
  { title: "(You Make Me Feel Like) A Natural Woman",  artist: "Aretha Franklin",               year: 1967 },
  { title: "No Scrubs",                                artist: "TLC",                           year: 1999 },
  { title: "Waterfalls",                               artist: "TLC",                           year: 1995 },
  { title: "Ain't No Mountain High Enough",            artist: "Marvin Gaye & Tammi Terrell",   year: 1967 },
  { title: "Killing Me Softly",                        artist: "Fugees",                        year: 1996 },

  // Obscure / deep cuts
  { title: "Tramp",                     artist: "Otis Redding & Carla Thomas", year: 1967 },
  { title: "Try a Little Tenderness",   artist: "Otis Redding",            year: 1966 },
  { title: "I've Been Loving You Too Long", artist: "Otis Redding",        year: 1965 },
  { title: "Backstabbers",              artist: "The O'Jays",              year: 1972 },
  { title: "For the Love of Money",     artist: "The O'Jays",              year: 1973 },
  { title: "Inner City Blues",          artist: "Marvin Gaye",             year: 1971 },
  { title: "Mercy Mercy Me",            artist: "Marvin Gaye",             year: 1971 },
  { title: "Déjà Vu",                   artist: "Dionne Warwick",          year: 1979 },
  { title: "Walk On By",                artist: "Dionne Warwick",          year: 1964 },
  { title: "Do I Do",                   artist: "Stevie Wonder",           year: 1982 },
  { title: "Living for the City",       artist: "Stevie Wonder",           year: 1974 },
  { title: "Higher Ground",             artist: "Stevie Wonder",           year: 1973 },
  { title: "Ball of Confusion",         artist: "The Temptations",         year: 1970 },
  { title: "Cloud Nine",                artist: "The Temptations",         year: 1969 },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye",     year: 1968 },
  { title: "Stop! In the Name of Love", artist: "The Supremes",            year: 1965 },
  { title: "You Keep Me Hangin' On",    artist: "The Supremes",            year: 1966 },
  { title: "Reach Out I'll Be There",   artist: "Four Tops",               year: 1966 },
  { title: "Standing in the Shadows of Love", artist: "Four Tops",        year: 1966 },
  { title: "It's the Same Old Song",    artist: "Four Tops",               year: 1965 },
];
